FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    git \
    openssh-server \
    openssh-client \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-venv \
 && rm -rf /var/lib/apt/lists/*

#RUN useradd -m user
#RUN mkdir -p /home/user/.ssh
RUN mkdir -p /home/user/data

COPY . /.

#WORKDIR /home/user/

RUN pip3 install --no-cache-dir -r requirements.txt

#RUN chown -R user:user /home/user/.ssh

#USER user

CMD ["python3", "-u", "./executor.py"]
