version: "3"
services:
  # The orchestrator
  mao1:
    build: .
    environment:
      # Directory to be used for storing datasets
      - importdir=/home/user/data
      # Username for elections
      - workuser=sonapi
      - etcdhost=0.0.0.0
      - port=2379
      - dbuser=scheduler
      - password=password
      - db=schedule
      - dbhost=0.0.0.0
      # Git credentials
      - gitemail=<>
      - gitusername=<>
    ports:
      - "8080:8080"
    volumes:
      # Mount the host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the data directories from the config file
      - /home/panos/tutorial:/home/user/data
      # Git config
      - /home/panos/dockerssh/keys/:/home/user/.ssh
    network_mode: "host"
    depends_on:
      - etcd
      - db
  # The jobstore for scheduling crawlers and etcd listeners
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=schedule
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    network_mode: "host"
  # The etcd node
  etcd:
    image: quay.io/coreos/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      # The name this node will be added to the cluster with
      - ETCD_NAME=etcd
      # Make sure this matches the volume
      - DATA-DIR=/etcd-data
      # Endpoint the peers in the cluster will use to talk to this node
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      # Endpoint this node is listening at for peer requests
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # Endpoint this node is listening at for client requests
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      # Endpoint clients can use to talk to this node
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      # The settings below need to be retrieved from an existing node
      # to join an existing cluster
      #- ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./etcd-data:/etcd-data
    network_mode: "host"
